version: '2'
services:
    vktrgt-app:
        image: vktrgt
        external_links:
            - vktrgt-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=vktrgt
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    vktrgt-mongodb:
        extends:
            file: mongodb.yml
            service: vktrgt-mongodb
