version: '2'
services:
    vktrgt-mongodb:
        container_name: vktrgt-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/vktrgt/mongodb/:/data/db/
